version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - "5498:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  oversite-backend:
    build: .
    container_name: oversite-backend
    ports:
      - "3001:3000"  # mapa puerto del host a contenedor
    restart: always
    depends_on:
      - db
      - minio
    env_file:
    - .env.local

  minio:
    image: minio/minio
    restart: always
    env_file:
    - .env.local
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Consola web
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  minio:
  
