version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5498:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
